version: '3.8'

services:
  iiif-openslide:
    image: mekarsalab/py-iiif:v1.2
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
    command: >
      sh -c "gunicorn -w ${GUNICORN_WORKERS:-2} -k gthread --threads ${GUNICORN_THREADS:-2} \
      -b 0.0.0.0:5050 wsgi:app --timeout ${GUNICORN_TIMEOUT:-120}"
    env_file:
      - .env
    environment:
      - PORT=5050
      - PYTHONBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=4
    networks:
      - openslide-net
      - swarm-net

  haproxy-lb:
    image: haproxy:alpine
    ports:
      - target: 80
        published: 8181
        protocol: tcp
        mode: host
      - target: 8404
        published: 8404
        protocol: tcp
        mode: host
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - openslide-net
      - swarm-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  openslide-net: 
    driver: overlay
  swarm-net:
    external: true
    # driver: overlay
    # attachable: true
