version: "3.9"
services:
  iiif-baseline:
    image: mekarsalab/py-iiif:v1.2
    ports:
      - "8181:5050"
    env_file:
      - .env
    command: >
      sh -c "gunicorn -w ${GUNICORN_WORKERS:-2}
      -k gthread --threads ${GUNICORN_THREADS:-2}
      -b 0.0.0.0:5050 wsgi:app"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
        reservations:
          cpus: "1"
          memory: 1g
